# Specify location of manifest files for each package manager
version: 2

updates:
  - package-ecosystem: "composer"
    # Files stored in `app` directory
    directory: "/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    # Files stored in `database` directory
    directory: "/database"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/.github"
    schedule:
      interval: "weekly"