# Specify location of manifest files for each package manager
version: 2

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

updates:
  - package-ecosystem: "composer"
    # Files stored in repository root
    directory: "/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    # Files stored in `app` directory
    directory: "/database"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    schedule:
      interval: "weekly"